pub const MalErr = error{
    BadHashMap,
    BadInput,
    InvalidArgs,
    IOError,
    LookupError,
    NotImplemented,
    OutOfBounds,
    OutOfMemory,
    Overflow,
    ThrowExcp,
    TypeError,
    UnmatchedParen,
    UnmatchedString,
};
